$kind: http-request
name: " product reviews"
description: ""
url: http://localhost:3000/api/v1/review
method: PUT
body:
  type: json
  content: "{\r

    \   \r

    \    \"productId\":\"6a8b8a6657642ccc6d6c23e4\",\r

    \    \"comment\":\"this is best product i india\",\r

    \    \"rating\":6\r

    }"
order: 339930543097127
